language: php

cache:
    directories:
        $HOME/.composer/cache/files

php:
    - 7.0

install:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer require satooshi/php-coveralls
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer update

script:
    - vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 -sp src tests
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls
